### PR TITLE
 fixes : #8 Integrate FFmpeg via WebAssembly for Video Processing 

### PR DESCRIPTION
**Pull request by adx04**
hello @Manav-Khandurie !
i have created the react app with login/signup that leads to a basic profile page that also has the functionality to logout as well
along with Firebase token Id generation and session mgmt. ...i have also included the "react-toastify" to noftify toast messages as a popup whenever the user is loggin in/signing up whether one is logged in successfully or not .

(edit)

i have also imported  and integrated ffmpeg in the videouploadcomponent for client side conversion and download feature of video into different formats such as mkv ,webm,mov etc. (in the /client folder as per you instructed)

### CODE REVIEW

**Comment by Manav-Khandurie** [comment]
Het @adx04  , there are some merge conflicts , please fix it and redo the pull

**Comment by adx04** [comment]
Ok @Manav-Khandurie !

**Comment by adx04** [comment]
i have fixed it @Manav-Khandurie !
i have removed my React-FIrebase and react toastify signup/signin/profile ..you won't consider my frontend right now as you megered rampantvoid's pull request for the frontend too?

**Comment by Manav-Khandurie** [comment]
> i have fixed it @Manav-Khandurie !
> i have removed my React-FIrebase and react toastify signup/signin/profile ..you won't consider my frontend right now as you megered rampantvoid's pull request for the frontend too?

Oh no i would consider it as an contribution to enhancement issue now which was in the works , that would allow you to get points for the contribution .

**Comment by adx04** [comment]
> > i have fixed it @Manav-Khandurie !
> > i have removed my React-FIrebase and react toastify signup/signin/profile ..you won't consider my frontend right now as you megered rampantvoid's pull request for the frontend too?
> 
> Oh no i would consider it as an contribution to enhancement issue now which was in the works , that would allow you to get points for the contribution .

So @Manav-Khandurie  where should I put my react folder separately for now?

**Comment by Manav-Khandurie** [comment]
> > > i have fixed it @Manav-Khandurie !
> > > i have removed my React-FIrebase and react toastify signup/signin/profile ..you won't consider my frontend right now as you megered rampantvoid's pull request for the frontend too?
> > 
> > Oh no i would consider it as an contribution to enhancement issue now which was in the works , that would allow you to get points for the contribution .
> 
> So @Manav-Khandurie  where should I put my react folder separately for now?



For now just create a enhancements folder in clinet and leave it there, will get back to it later

**Pull request merged**
